# ----------------------------------
#          INSTALL & TEST
# ----------------------------------
install_requirements:
	@pip install -r requirements.txt

# ----------------------------------
#     		  RUN FULLSTACK
# ----------------------------------
run_fullstack:
	@streamlit run Home.py